# 卷積

In [1]:
import warnings

# 忽略警告
warnings.filterwarnings("ignore")

## 範例1. 使用程式計算卷積

In [2]:
import numpy as np

# 測試資料
source_map = np.array(list("1110001110001110011001100")).astype(np.int64)
source_map = source_map.reshape(5, 5)
print("原始資料：")
print(source_map)

# 濾波器(Filter)
filter1 = np.array(list("101010101")).astype(np.int64).reshape(3, 3)
print("\n濾波器:")
print(filter1)

原始資料：
[[1 1 1 0 0]
 [0 1 1 1 0]
 [0 0 1 1 1]
 [0 0 1 1 0]
 [0 1 1 0 0]]

濾波器:
[[1 0 1]
 [0 1 0]
 [1 0 1]]


In [3]:
# 計算第一個卷積
source_map1 = source_map[0:3, 0:3]
np.sum(source_map1 * filter1)

4

In [4]:
# 計算卷積
# 初始化計算結果的矩陣
width = height = source_map.shape[0] - filter1.shape[0] + 1
result = np.zeros((width, height))

# 計算每一格
for i in range(width):
    for j in range(height):
        value1 = (
            source_map[i : i + filter1.shape[0], j : j + filter1.shape[1]] * filter1
        )
        result[i, j] = np.sum(value1)
print(result)

[[4. 3. 4.]
 [2. 4. 3.]
 [2. 3. 4.]]


In [5]:
# 使用 scipy 計算卷積
from scipy.signal import convolve2d

# convolve2d：二維卷積
convolve2d(source_map, filter1, mode="valid")

array([[4, 3, 4],
       [2, 4, 3],
       [2, 3, 4]])

In [6]:
# 使用 scipy 計算卷積, padding ='same'
from scipy.signal import convolve2d

# convolve2d：二維卷積
convolve2d(source_map, filter1, mode="same")

array([[2, 2, 3, 1, 1],
       [1, 4, 3, 4, 1],
       [1, 2, 4, 3, 3],
       [1, 2, 3, 4, 1],
       [0, 2, 2, 1, 1]])